kind: Service
apiVersion: v1
metadata:
  name: rainbow-mnemonic
spec:
  type: NodePort
  selector:
    app: rainbow-mnemonic
    # this is the key here - it allows us to match only pods of the currently active color
    color: "__COLOR__"
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rainbow-mnemonic-__COLOR__
  labels:
    app: rainbow-mnemonic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rainbow-mnemonic
  template:
    metadata:
      labels:
        app: rainbow-mnemonic
        color: "__COLOR__"
    spec:
      containers:
      - name: rainbow-deploy
        image: gcr.io/maas-kube-rainbow/rainbow-mnemonic:__COLOR__
        ports:
        - containerPort: 8080